[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.8,<3.14"
pip = "*"
setuptools = "*"
wheel = "*"
hatchling = "*"
scikit-build-core = ">=0.10,<1"
pybind11 = ">=3,<4"
cmake = ">=3.20,<4"
ninja = ">=0.13.2,<2"
pre-commit = ">=4.4.0,<5"

[feature.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-benchmark = "*"
scikit-image = "*"
isort = "*"
jupyter = "*"
pandas = "*"

[feature.dev.pypi-dependencies]
napari = { extras = ["all"], version = "*" }

[feature.build.dependencies]
python-build = "*"
cibuildwheel = "*"

[tasks]
build-ocl = "pip install -e . && pip install -e ./backends/opencl -v"
build-cuda = "pip install -e . && pip install -e ./backends/cuda -v"
build-all = "pip install -e . && pip install -e ./backends/opencl -v && pip install -e ./backends/cuda -v"
test-cuda = "pytest -k cuda -v"
test-ocl = "pytest -k opencl -v"
test = "pytest -v"

[environments]
default = { features = ["dev"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }
