
// this code is auto-generated by the script 'pyclesperanto_autogen_tier_script.ipynb'.
// Do not edit manually. Instead, edit the script and run it again.
    
#include "pycle_wrapper.hpp"
#include "tier7.hpp"

namespace py = pybind11;

auto tier7_(py::module &m) -> void {

    
m.def("_affine_transform", &cle::tier7::affine_transform_func, "Call affine_transform from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("transform_matrix"), py::arg("interpolate"), py::arg("resize"));

	
m.def("_eroded_otsu_labeling", &cle::tier7::eroded_otsu_labeling_func, "Call eroded_otsu_labeling from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("number_of_erosions"), py::arg("outline_sigma"));

	
m.def("_rigid_transform", &cle::tier7::rigid_transform_func, "Call rigid_transform from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("translate_x"), py::arg("translate_y"), py::arg("translate_z"), py::arg("angle_x"), py::arg("angle_y"), py::arg("angle_z"), py::arg("centered"), py::arg("interpolate"), py::arg("resize"));

	
m.def("_rotate", &cle::tier7::rotate_func, "Call rotate from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("angle_x"), py::arg("angle_y"), py::arg("angle_z"), py::arg("centered"), py::arg("interpolate"), py::arg("resize"));

	
m.def("_scale", &cle::tier7::scale_func, "Call scale from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("factor_x"), py::arg("factor_y"), py::arg("factor_z"), py::arg("centered"), py::arg("interpolate"), py::arg("resize"));

	
m.def("_translate", &cle::tier7::translate_func, "Call translate from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("translate_x"), py::arg("translate_y"), py::arg("translate_z"), py::arg("interpolate"));

	
m.def("_closing_labels", &cle::tier7::closing_labels_func, "Call closing_labels from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("radius"));

	
m.def("_erode_connected_labels", &cle::tier7::erode_connected_labels_func, "Call erode_connected_labels from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("radius"));

	
m.def("_opening_labels", &cle::tier7::opening_labels_func, "Call opening_labels from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("radius"));

	
m.def("_voronoi_otsu_labeling", &cle::tier7::voronoi_otsu_labeling_func, "Call voronoi_otsu_labeling from C++.",
    py::return_value_policy::take_ownership,
    py::arg("device"), py::arg("src"), py::arg("dst"), py::arg("spot_sigma"), py::arg("outline_sigma"));


}
