
# this code is auto-generated by the script 'pyclesperanto_autogen_tier_script.ipynb'.
# Do not edit manually. Instead, edit the script and run it again.

from ._core import Device
from ._array import Image, Array
from ._decorators import plugin_function



@plugin_function
def flag_existing_labels(
    input_image: Image,
	output_image: Image = None,
	device: Device = None
) -> Image:
    from ._pyclesperanto import _flag_existing_labels as op
    # op = _cle._flag_existing_labels
    
    return op(
        device=device,
		src=input_image,
		dst=output_image
    )


@plugin_function
def gamma_correction(
    input_image: Image,
	output_image: Image = None,
	gamma: float = 0,
	device: Device = None
) -> Image:
    from ._pyclesperanto import _gamma_correction as op
    # op = _cle._gamma_correction
    
    return op(
        device=device,
		src=input_image,
		dst=output_image,
		gamma=float(gamma)
    )


@plugin_function
def mean_of_all_pixels(
    input_image: Image,
	device: Device = None
) -> float:
    from ._pyclesperanto import _mean_of_all_pixels as op
    # op = _cle._mean_of_all_pixels
    
    return op(
        device=device,
		src=input_image
    )

