# this code is auto-generated by the script 'pyclesperanto_autogen_tier_script.ipynb'.
# Do not edit manually. Instead, edit the script and run it again.

from ._core import Device
from ._array import Image, Array
from ._decorators import plugin_function


@plugin_function
def difference_of_gaussian(
    input_image: Image,
    output_image: Image = None,
    sigma1_x: float = 0,
    sigma1_y: float = 0,
    sigma1_z: float = 0,
    sigma2_x: float = 0,
    sigma2_y: float = 0,
    sigma2_z: float = 0,
    device: Device = None,
) -> Image:
    from ._pyclesperanto import _difference_of_gaussian as op

    return op(
        device=device,
        src=input_image,
        dst=output_image,
        sigma1_x=float(sigma1_x),
        sigma1_y=float(sigma1_y),
        sigma1_z=float(sigma1_z),
        sigma2_x=float(sigma2_x),
        sigma2_y=float(sigma2_y),
        sigma2_z=float(sigma2_z),
    )


@plugin_function
def maximum_of_all_pixels(
    input_image: Image, output_image: Image = None, device: Device = None
) -> Image:
    from ._pyclesperanto import _maximum_of_all_pixels as op

    return op(device=device, src=input_image, dst=output_image)
