{% set name = "pyclesperanto" %}
{% set version = "0.7.1" %}
{% set sha256 = "1f65cc7e9f8348faf4299c3aed1e4873c2b2db8e358f244d9664564054a40309" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - {{ compiler('cxx') }}
  host:
    - python
    - scikit-build-core
    - pybind11
    - cmake
    - khronos-opencl-icd-loader      # [win or osx]
    - ocl-icd      # [linux]
  run:
    - python
    - numpy
    - toolz
    - matplotlib-base
    - khronos-opencl-icd-loader      # [win or osx]
    - ocl-icd      # [linux]

test:
  imports:
    - pyclesperanto
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
    home: https://pypi.org/project/pyclesperanto/
    doc_url: https://clesperanto.github.io/pyclesperanto/
    dev_url: https://github.com/clEsperanto/pyclesperanto/
    license: BSD-3-Clause
    license_file: LICENSE
    summary: GPU-accelerated Image Processing library using OpenCL
    description: |
        pyclesperanto is the python package of clEsperanto - a multi-language framework for GPU-accelerated image processing.
        clEsperanto uses OpenCL kernels extended with CLIJ custom syntax.
extra:
    recipe-maintainers:
        - StRigaud
        - haesleinhuepf
