name: auto-update-pr

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  handle-custom-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print release tag
        run: |
          echo "Received release tag: ${{ github.event.client_payload.release_tag }}"
