name: auto-update-pr

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  handle-custom-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print release tag
        run: |
          echo "Received release tag: ${{ github.event.client_payload.release_tag }} from CLIc"


      - name: Checkout
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Install GitHub CLI
        run: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh


      - name: Configure git
        run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"


      - name: Create a new issue with the release tag
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
          ISSUE_TITLE="Auto-update pyclesperanto to version ${{ github.event.client_payload.release_tag }}"
          EXISTING_ISSUE_NUMBER=$(gh issue list --search "$ISSUE_TITLE" --json number,title --jq '.[] | select(.title == env.ISSUE_TITLE) | .number')
          if [ -z "$EXISTING_ISSUE_NUMBER" ]; then
            ISSUE_NUMBER=$(gh issue create --title "$ISSUE_TITLE" \
            --body $'## Auto-update pyclesperanto\n\nThis issue has been automatically created by the auto-update workflow.\n\n### Update Details\n- **pyclesperanto Version:** ${{ github.event.client_payload.release_tag }}\n- **CLIc Version:** ${{ github.event.client_payload.release_tag }}\n\n### Action Required\nPlease update pyclesperanto to the specified version.\n\n### Additional Information\nFor more details, refer to the [Release Notes](https://github.com/clEsperanto/CLIc/releases/tag/${{ github.event.client_payload.release_tag }}).\n\nThank you!' \
            --label "auto-update" --json number --jq '.number')
          else
            gh issue comment $EXISTING_ISSUE_NUMBER --body $'## Auto-update pyclesperanto\n\nThis issue has been automatically updated by the auto-update workflow.\n\n### Update Details\n- **pyclesperanto Version:** ${{ github.event.client_payload.release_tag }}\n- **CLIc Version:** ${{ github.event.client_payload.release_tag }}\n\n### Action Required\nPlease update pyclesperanto to the specified version.\n\n### Additional Information\nFor more details, refer to the [Release Notes](https://github.com/clEsperanto/CLIc/releases/tag/${{ github.event.client_payload.release_tag }}).\n\nThank you!'
            ISSUE_NUMBER=$EXISTING_ISSUE_NUMBER
          fi
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV


      - name: get gencle and update pyclesperanto
        env:
            GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
            git clone https://$GH_TOKEN@github.com/clEsperanto/gencle.git gencle
            python ./gencle/pyclesperanto_auto_update.py ${{ github.workspace }} "clEsperanto/CLIc" ${{ github.event.inputs.release_tag }}


      - name: Branch, Commit, and push changes
        env:
            GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
          git checkout -b auto-update-${{ github.event.inputs.release_tag }}
          git add .
          git commit -m "auto-update pyclesperanto to version ${{ github.event.inputs.release_tag }}"
          git push origin auto-update-${{ github.event.inputs.release_tag }}


      - name: Create Pull Request
        env:
            GH_TOKEN: "${{ secrets.RELEASE_PAT }}"
            ISSUE_NUMBER: ${{ steps.create_issue.outputs.ISSUE_NUMBER }}
        run: |
            gh auth login --with-token <<< "${{ secrets.RELEASE_PAT }}"
            gh pr create \
                --title "Auto-update pyclesperanto to version ${{ github.event.client_payload.release_tag }}." \
                --body $'This PR updates pyclesperanto tiers code to `clEsperanto/CLIc@${{ github.event.client_payload.release_tag }}`.\n\ncloses #${{ env.ISSUE_NUMBER }}'' \
                --head auto-update-${{ github.event.client_payload.release_tag }} \
                --base main \
                --label "auto-update"
