name: Auto Update

on:
  repository_dispatch:
    types: [clic_update]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'CLIc tag'
        required: true
        default: 'master'

jobs:
  run-cle-roboto:
    runs-on: ubuntu-latest
    steps:
      - name: Print release tag
        env:
          RELEASE_TAG: ${{ github.event.client_payload.release_tag || github.event.inputs.release_tag }}
        run: |
          echo "Received release tag: $RELEASE_TAG from CLIc"
