name: Auto Update

on:
  repository_dispatch:
    types: [clic_update]

jobs:
  handle-custom-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print release tag
        run: |
          echo "Received release tag: ${{ github.event.client_payload.release_tag }} from CLIc"
