name: auto-update-pr

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  handle-custom-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print release tag
        run: |
          echo "Received release tag: ${{ github.event.client_payload.release_tag }} from CLIc"


      - name: Checkout
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Install GitHub CLI
        run: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh


      - name: Configure git
        run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"


      - name: Create a new issue with the release tag
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
            gh issue create --title "Auto-update pyclesperanto to version ${{ github.event.client_payload.release_tag }}" \
            --body "This issue is created by the auto-update workflow.\npyclesperanto can be updated with the CLIc version ${{ github.event.client_payload.release_tag }}.\n\nSee [Release Notes](https://github.com/clEsperanto/CLIc/releases/tag/${{ github.event.client_payload.release_tag }})" \
            --label "auto-update"
            export ISSUE_NUMBER=$(gh issue list --label "auto-update" --limit 1 --json number --jq '.[0].number')


      - name: get gencle and update pyclesperanto
        env:
            GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
            git clone https://$GH_TOKEN@github.com/clEsperanto/gencle.git gencle
            python ./gencle/pyclesperanto_auto_update.py ${{ github.workspace }} "clEsperanto/CLIc" ${{ github.event.inputs.release_tag }}


      - name: Branch, Commit, and push changes
        env:
            GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
          git checkout -b auto-update-${{ github.event.inputs.release_tag }}
          git add .
          git commit -m "auto-update pyclesperanto to version ${{ github.event.inputs.release_tag }}"
          git push origin auto-update-${{ github.event.inputs.release_tag }}


      - name: Create Pull Request
        env:
            GH_TOKEN: "${{ secrets.RELEASE_PAT }}"
            ISSUE_NUMBER: ${{ steps.create_issue.outputs.ISSUE_NUMBER }}
        run: |
            gh auth login --with-token <<< "${{ secrets.RELEASE_PAT }}"
            gh pr create \
                --title "Auto-update pyclesperanto to version ${{ github.event.client_payload.release_tag }}." \
                --body "This PR updates pyclesperanto tiers code to `clEsperanto/CLIc@${{ github.event.client_payload.release_tag }}`.\n\ncloses #${{ env.ISSUE_NUMBER }}" \
                --head auto-update-${{ github.event.client_payload.release_tag }} \
                --base main \
                --label "auto-update"
