name: CLIC release PR

on:
  repository_dispatch:
    types: [new_release]

jobs:
  handle-new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Handle new release
        run: |
          echo "New release detected from target repository"
          # Add your actions here, e.g., create an issue, send a notification, etc.
